_GIT_CONFIG_BASE_SECTION = "gitcache"

GIT_CONFIG_USE_LOCK = f"{_GIT_CONFIG_BASE_SECTION}.uselock"
"""git config key for use-lock option"""
GIT_CONFIG_ROOT_DIR = f"{_GIT_CONFIG_BASE_SECTION}.rootdir"
"""git config key for root dir"""
GIT_CONFIG_CLONE_MODE = f"{_GIT_CONFIG_BASE_SECTION}.clonemode"
"""git config key for clone mode"""
GIT_CONFIG_LOCK_TIMEOUT = f"{_GIT_CONFIG_BASE_SECTION}.locktimeout"
"""git config key for lock timeout"""
GIT_CONFIG_METADATA_STORE_MODE = f"{_GIT_CONFIG_BASE_SECTION}.storemode"
"""git config key for metadata store mode"""
